" install vim-plug automatically
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'terryma/vim-multiple-cursors'
Plug 'noahfrederick/vim-noctu'

call plug#end()

syntax on 
set encoding=utf-8
set number
set ruler
set hlsearch

colo noctu

"" Golang
" run goimports along gofmt on each save
let g:go_fmt_command = "goimports"
